### ISSUE TITLE
Having a trusted custom visual

### ISSUE THREAD

**Issue by TonyGaul** [Microsoft/PowerBI-visuals-docs#43]
Hi, I am experiencing a couple of limitations with the sandboxed IFrame and was wondering if it was possible to have a trusted custom visual and allow it to behave like the default visuals?

Some limitations are:
- Tool tips don't extend past the IFrame / boundary of the custom visual.  This is not an issue with the default visuals.  Sometimes I am using a small custom visual and don't have a lot of room to display the tooltip inside the IFrame boundary.
- I can't open a URL in the same browser tab.  The best I can do is to open the URL in a new tab.  The idea here was to click through to another Power BI report from the custom visual.  I don't want to pin the custom visual to a dashboard to have this functionality, I would like to do this from the report / pinned live report.

Cheers,
Tony

**Comment by spatney** [comment]
IFrame is not only a question of trust. It is also to do with script/css isolation. For example if you wanted to move to a different D3(other any JS library) version than what another "trusted" or core visual use, you wouldn't be able to. 

For your problems we do have solutions on our road-map. We will be providing tool-tips as a service, and since the tool-tip DOM will belong to PowerBI the iFrame boundary won't be an issue.  Similarly the url navigation can be exposed as a service.

**Comment by TonyGaul** [comment]
Great, thanks for the update!

**Comment by TonyGaul** [comment]
Hi Sachin, I noticed this issue is closed.  Just wondering is the URL navigation as a service on the roadmap?  If not, what would it take to get that functionality added?  Tks Tony

**Comment by spatney** [comment]
I closed this because we have no plans to have trusted custom visuals. The URL navigation is on the backlog (internal), and we don't add it [here](https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/Roadmap/README.md) unless we have some idea when to expect it.

**Comment by TonyGaul** [comment]
That's all I was after. Cheers.
